In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
a = np.array([4,5,68,2])

In [4]:
type(a)

numpy.ndarray

In [5]:
print(a)

[ 4  5 68  2]


In [6]:
a

array([ 4,  5, 68,  2])

In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

In [9]:
a.size

4

In [10]:
a.dtype

dtype('int32')

In [11]:
a

array([ 4,  5, 68,  2])

In [12]:
a.sum()

79

In [13]:
a.max()

68

In [14]:
a.argmax()

2

In [15]:
a.mean()

19.75

In [16]:
a[:3]

array([ 4,  5, 68])

In [17]:
a[0]

4

In [18]:
b = np.array([[3,6,19],[9,10,11]])

In [19]:
b.shape

(2, 3)

In [20]:
b

array([[ 3,  6, 19],
       [ 9, 10, 11]])

In [24]:
b[0,1]

6

In [25]:
b[0,1:]

array([ 6, 19])

In [30]:
b[:,1]

array([ 6, 10])

In [31]:
b[:,1:2]

array([[ 6],
       [10]])